redirects:
    # Installation
    installation/upgrade_notes:       ./installation/upgrade-notes.md
    installation/supported_platforms: ./installation/supported-platforms.md

    # Inputs
    input/collectd:        ./pipeline/inputs/
    input/cpu:             ./pipeline/inputs/cpu-metrics.md
    input/disk:            ./pipeline/inputs/disk-io-metrics.md
    #inputs/docker:          ./pipeline/inputs/
    input/dummy:           ./pipeline/inputs/dummy.md
    input/exec:            ./pipeline/inputs/exec.md
    input/forward:         ./pipeline/inputs/forward.md
    input/head:            ./pipeline/inputs/head.md
    input/health:          ./pipeline/inputs/health.md
    input/kmsg:            ./pipeline/inputs/kernel-logs.md
    input/mem:             ./pipeline/inputs/memory-metrics.md
    input/mqtt:            ./pipeline/inputs/mqtt.md
    input/netif:           ./pipeline/inputs/network-io-metrics.md
    input/proc:            ./pipeline/inputs/process.md
    input/random:          ./pipeline/inputs/random.md
    input/serial:          ./pipeline/inputs/serial-interface.md
    #inputs/statsd:          ./pipeline/inputs/
    input/stdin:           ./pipeline/inputs/standard-input.md
    input/syslog:          ./pipeline/inputs/syslog.md
    input/systemd:         ./pipeline/inputs/systemd.md
    input/tail:            ./pipeline/inputs/tail.md
    input/tcp:             ./pipeline/inputs/tcp.md
    input/thermal:         ./pipeline/inputs/thermal.md
    input/winlog:          ./pipeline/inputs/windows-event-log.md

    # Filters
    filter/aws:             ./pipeline/filters/aws-metadata.md
    filter/grep:            ./pipeline/filters/grep.md
    filter/kubernetes:      ./pipeline/filters/kubernetes.md
    filter/lua:             ./pipeline/filters/lua.md
    filter/modify:          ./pipeline/filters/modify.md
    filter/nest:            ./pipeline/filters/nest.md
    filter/parser:          ./pipeline/filters/parser.md
    filter/record_modifier: ./pipeline/filters/record-modifier.md
    filter/rewrite_tag:     ./pipeline/filters/rewrite-tag.md
    filter/stdout:          ./pipeline/filters/standard-output.md
    filter/throttle:        ./pipeline/filters/throttle.md

    # Outputs
    output/azure:          ./pipeline/outputs/azure.md
    output/bigquery:       ./pipeline/outputs/bigquery.md
    output/counter:        ./pipeline/outputs/counter.md
    output/cloudwatch:     ./pipeline/outputs/cloudwatch.md
    output/datadog:        ./pipeline/outputs/datadog.md
    output/es:             ./pipeline/outputs/elasticsearch.md
    output/file:           ./pipeline/outputs/file.md
    output/firehose:       ./pipeline/outputs/firehose.md
    output/flowcounter:    ./pipeline/outputs/flowcounter.md
    output/forward:        ./pipeline/outputs/forward.md
    output/gelf:           ./pipeline/outputs/gelf.md
    output/http:           ./pipeline/outputs/http.md
    output/influxdb:       ./pipeline/outputs/influxdb.md
    output/kafka:          ./pipeline/outputs/kafka.md
    output/kafka_rest:     ./pipeline/outputs/kafka-rest-proxy.md
    output/nats:           ./pipeline/outputs/nats.md
    output/null:           ./pipeline/outputs/null.md
    output/s3:             ./pipeline/outputs/s3.md
    output/slack:          ./pipeline/outputs/slack.md
    output/splunk:         ./pipeline/outputs/splunk.md
    output/stackdriver:    ./pipeline/outputs/stackdriver.md
    output/stdout:         ./pipeline/outputs/standard-output.md
    output/tcp:            ./pipeline/outputs/tcp-and-tls.md
    output/td:             ./pipeline/outputs/treasure-data.md
