name: Link checks

on:
  schedule:
    - cron: "00 18 1 * *"
  pull_request:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # required for peter-evans/create-issue-from-file
      issues: write
    steps:
      - uses: actions/checkout@v7

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: --accept '100..=103,200..=299,401,403,429,999' --verbose --no-progress .
          # Fail if PR is opened with broken links, but don't fail on scheduled runs.
          fail: ${{ github.event_name == 'pull_request' }}
          jobSummary: true

      - name: Create Issue From File
        if: ${{ github.event_name != 'pull_request' && steps.lychee.outputs.exit_code != 0 }}
        uses: peter-evans/create-issue-from-file@v6
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
